// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_professional = "CgkItef62N0LEAIQBg"; // <GPGSID>
        public const string leaderboard = "CgkItef62N0LEAIQAw"; // <GPGSID>
        public const string achievement_50_candies = "CgkItef62N0LEAIQBA"; // <GPGSID>
        public const string achievement_you_did_your_best = "CgkItef62N0LEAIQCQ"; // <GPGSID>
        public const string achievement_100_candies = "CgkItef62N0LEAIQBQ"; // <GPGSID>
        public const string achievement_survival_of_the_fittest = "CgkItef62N0LEAIQCA"; // <GPGSID>

}

